// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class GameFriendListChatData
{
    public int FriendId { get; set; }

    public int ChatRoomId { get; set; }
}