// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class GameTaskList
{
    public int TaskId { get; set; }

    public string TaskName { get; set; }

    public string TaskDescription { get; set; }

    public decimal TaskReward { get; set; }

    public int TaskConditionId { get; set; }

    public virtual GameMemberTask Task { get; set; }

    public virtual GameTaskConditionData TaskCondition { get; set; }
}