// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class GameShopAnnouncement
{
    public int AnnouncementId { get; set; }

    public string AnnouncementTitle { get; set; }

    public string AnnouncementContent { get; set; }

    public byte[] AnnouncementImageHeader { get; set; }

    public int AdminId { get; set; }

    public DateTime EditTime { get; set; }

    public DateTime PublishTime { get; set; }

    public bool DisplayOrNot { get; set; }

    public bool SyncWithGameAndShopDisplay { get; set; }

    public bool HideInGameDisplay { get; set; }

    public bool ConvertToMarquee { get; set; }

    public bool PinToTop { get; set; }

    public int AnnouncementTypeId { get; set; }

    public string AnnouncementImageContent { get; set; }

    public virtual ShopGameAdminData Admin { get; set; }

    public virtual AnnouncementTypeData AnnouncementType { get; set; }
}