// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class Game1on1MessageData
{
    public int MessageId { get; set; }

    public int DialogueId { get; set; }

    public int? SenderId { get; set; }

    public int? ReceiverId { get; set; }

    public string ReceiverContent { get; set; }

    public DateTime? SentTime { get; set; }

    public int? GroupId { get; set; }

    public virtual ShopMemberInfo Receiver { get; set; }

    public virtual ShopMemberInfo Sender { get; set; }
}