// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class ShopOrderStatusData
{
    public int OrderStatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<ShopOrderTotalTable> ShopOrderTotalTable { get; set; } = new List<ShopOrderTotalTable>();
}