// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class ShopMemberInfo
{
    public int MemberId { get; set; }

    public string MemberAccount { get; set; }

    public string CharacterName { get; set; }

    public int? LevelId { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateTime? Birthday { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public int? CatCoinQuantity { get; set; }

    public int? LoyaltyPoints { get; set; }

    public DateTime? RegistrationTime { get; set; }

    public DateTime? LastLoginTime { get; set; }

    public int? FavoriteId { get; set; }

    public int? CheckinDayCount { get; set; }

    public int? MyCatNameListId { get; set; }

    public int? RunGameHighestScore { get; set; }

    public virtual ICollection<Game1on1MessageData> Game1on1MessageDataReceiver { get; set; } = new List<Game1on1MessageData>();

    public virtual ICollection<Game1on1MessageData> Game1on1MessageDataSender { get; set; } = new List<Game1on1MessageData>();

    public virtual ICollection<GameCoinExchangeRecord> GameCoinExchangeRecord { get; set; } = new List<GameCoinExchangeRecord>();

    public virtual ICollection<GameFriendData> GameFriendDataFriend { get; set; } = new List<GameFriendData>();

    public virtual ICollection<GameFriendData> GameFriendDataMember { get; set; } = new List<GameFriendData>();

    public virtual ICollection<GameGlobalChatData> GameGlobalChatData { get; set; } = new List<GameGlobalChatData>();

    public virtual ICollection<GameMemberTask> GameMemberTask { get; set; } = new List<GameMemberTask>();

    public virtual GameRankData Level { get; set; }

    public virtual ShopMyCatNameList MyCatNameList { get; set; }

    public virtual ICollection<ShopCatStatus> ShopCatStatus { get; set; } = new List<ShopCatStatus>();

    public virtual ICollection<ShopCommonAddressData> ShopCommonAddressData { get; set; } = new List<ShopCommonAddressData>();

    public virtual ICollection<ShopFavoriteDataTable> ShopFavoriteDataTable { get; set; } = new List<ShopFavoriteDataTable>();

    public virtual ICollection<ShopMemberComplaintCase> ShopMemberComplaintCase { get; set; } = new List<ShopMemberComplaintCase>();

    public virtual ICollection<ShopMemberCouponData> ShopMemberCouponData { get; set; } = new List<ShopMemberCouponData>();

    public virtual ICollection<ShopMyCatNameList> ShopMyCatNameList { get; set; } = new List<ShopMyCatNameList>();

    public virtual ICollection<ShopOrderTotalTable> ShopOrderTotalTable { get; set; } = new List<ShopOrderTotalTable>();

    public virtual ICollection<ShopProductReviewTable> ShopProductReviewTable { get; set; } = new List<ShopProductReviewTable>();
}