// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.YaolinModels;

public partial class ShopProductReviewTable
{
    public int? MemberId { get; set; }

    public int? ProductId { get; set; }

    public string ReviewContent { get; set; }

    public int? ProductRating { get; set; }

    public int ProductReviewId { get; set; }

    public virtual ShopMemberInfo Member { get; set; }

    public virtual ShopProductTotal Product { get; set; }
}