// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameShopBanner
{
    public int BannerId { get; set; }

    public string Banner { get; set; }

    public DateTime? PublishDate { get; set; }

    public string Link { get; set; }

    public string ToPage { get; set; }

    public bool? Display { get; set; }
}