// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameMemberBMessageData
{
    public int MemberBId { get; set; }

    public string 訊息發送者內容 { get; set; }

    public DateTime? SentTime { get; set; }
}