// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameTaskConditionData
{
    public int TaskConditionId { get; set; }

    public string ConditionName { get; set; }

    public virtual ICollection<GameAchievementList> GameAchievementList { get; set; } = new List<GameAchievementList>();

    public virtual ICollection<GameTaskList> GameTaskList { get; set; } = new List<GameTaskList>();
}