// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameGlobalChatData
{
    public int? MemberId { get; set; }

    public int MessageId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? SentTime { get; set; }

    public bool? HideMessage { get; set; }

    public virtual ShopMemberInfo Member { get; set; }
}