// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameRankData
{
    public int RankId { get; set; }

    public string RankName { get; set; }

    public virtual ICollection<ShopMemberInfo> ShopMemberInfo { get; set; } = new List<ShopMemberInfo>();
}