// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameShopBlogData
{
    public int BlogArticleId { get; set; }

    public string ArticleTitle { get; set; }

    public string ArticleContent { get; set; }

    public DateTime? PublishTime { get; set; }

    public int? AdminId { get; set; }

    public bool? DisplayStatus { get; set; }

    public bool? PinToTop { get; set; }

    public bool? SyncWithGameAndShopDisplay { get; set; }

    public int? ArticleTypeId { get; set; }

    public virtual ShopGameAdminData Admin { get; set; }

    public virtual GameShopArticleType ArticleType { get; set; }
}