// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GamePetTotal
{
    public string CharacterName { get; set; }

    public string PetName { get; set; }

    public string PetLevel { get; set; }

    public string PetSkill { get; set; }
}