// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameMemberTask
{
    public int MemberTaskId { get; set; }

    public int? MemberId { get; set; }

    public int? TaskId { get; set; }

    public int? TaskProgress { get; set; }

    public DateTime? CompleteDate { get; set; }

    public virtual ShopMemberInfo Member { get; set; }

    public virtual GameTaskList Task { get; set; }
}