// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameShopArticleType
{
    public int ArticleTypeId { get; set; }

    public string ArticleTypeName { get; set; }

    public virtual ICollection<GameShopBlogData> GameShopBlogData { get; set; } = new List<GameShopBlogData>();
}