// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameMessageDatas
{
    public int MessageId { get; set; }

    public string Message { get; set; }

    public int? MemberId { get; set; }

    public DateTime? Timestamp { get; set; }
}