// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameAchievementRewardList
{
    public int AchievementRewardId { get; set; }

    public string AchievementRewardName { get; set; }

    public virtual ICollection<GameAchievementList> GameAchievementList { get; set; } = new List<GameAchievementList>();
}