// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class GameMessageData
{
    public int ChatRoomId { get; set; }

    public int MemberBId { get; set; }

    public virtual GameFriendListChatData ChatRoom { get; set; }

    public virtual GameMemberBMessageData MemberB { get; set; }
}