// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class MessageTypeData
{
    public int MessageTypeId { get; set; }

    public string MessageType { get; set; }
}