// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class Newsletter
{
    public int NewsletterId { get; set; }

    public int? TemplateId { get; set; }

    public string Subject { get; set; }

    public string ContentImage { get; set; }

    public DateTime? SendDate { get; set; }

    public string ImageUrl { get; set; }
}