// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopNavbarChild
{
    public int NavbarChildId { get; set; }

    public string NavText { get; set; }

    public int? NavbarId { get; set; }

    public virtual ShopNavbarList Navbar { get; set; }
}