// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopProductSpecification
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public string Specification { get; set; }

    public bool? Disable { get; set; }

    public virtual ShopProductTotal Product { get; set; }

    public virtual ICollection<ShopProductTotal> ShopProductTotal { get; set; } = new List<ShopProductTotal>();
}