// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopOrderTotalTable
{
    public int? MemberId { get; set; }

    public int OrderId { get; set; }

    public DateTime? OrderCreationDate { get; set; }

    public DateTime? LastUpdateTime { get; set; }

    public int? AddressId { get; set; }

    public string RecipientAddress { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public int? OrderStatusId { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? CouponId { get; set; }

    public int? ShippingMethodId { get; set; }

    public decimal? ResultPrice { get; set; }

    public virtual ShopCommonAddressData Address { get; set; }

    public virtual ICollection<EcpayOrders> EcpayOrders { get; set; } = new List<EcpayOrders>();

    public virtual ShopMemberInfo Member { get; set; }

    public virtual ShopOrderStatusData OrderStatus { get; set; }

    public virtual ShopPaymentMethodData PaymentMethod { get; set; }

    public virtual ShopShippingMethod ShippingMethod { get; set; }

    public virtual ICollection<ShopOrderDetailTable> ShopOrderDetailTable { get; set; } = new List<ShopOrderDetailTable>();

    public virtual ICollection<ShopProductReviewTable> ShopProductReviewTable { get; set; } = new List<ShopProductReviewTable>();
}