// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCommonshopName
{
    public int ShopId { get; set; }

    public string CityName { get; set; }

    public string DiscitcName { get; set; }

    public string ShopName { get; set; }

    public virtual ICollection<ShopCommonShop> ShopCommonShop { get; set; } = new List<ShopCommonShop>();
}