// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopReplyData
{
    public int ReplyId { get; set; }

    public int ComplaintCaseId { get; set; }

    public int ReceiverIdOfficial { get; set; }

    public string MessageRecipientContent { get; set; }

    public DateTime SentTime { get; set; }

    public virtual ShopMemberComplaintCase ComplaintCase { get; set; }

    public virtual ShopGameAdminData ReceiverIdOfficialNavigation { get; set; }
}