// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCatcharacter
{
    public int CatPersonalityId { get; set; }

    public string Personality { get; set; }

    public virtual ICollection<ShopCatStatus> ShopCatStatus { get; set; } = new List<ShopCatStatus>();
}