// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopComplaintStatusData
{
    public int ComplaintStatusId { get; set; }

    public string ComplaintStatusName { get; set; }

    public virtual ICollection<ShopMemberComplaintCase> ShopMemberComplaintCase { get; set; } = new List<ShopMemberComplaintCase>();
}