// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCommonShop
{
    public int Id { get; set; }

    public int? CommShopId { get; set; }

    public int? MemberId { get; set; }

    public virtual ShopCommonshopName CommShop { get; set; }

    public virtual ShopMemberInfo Member { get; set; }
}