// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopProductImageTable
{
    public int? ProductId { get; set; }

    public string ProductPhoto { get; set; }

    public int ProductImageId { get; set; }

    public bool? FrontCover { get; set; }

    public virtual ShopProductTotal Product { get; set; }
}