// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopReturnDataTable
{
    public int? OrderId { get; set; }

    public int? ReturnReasonId { get; set; }

    public int? ProcessingStatusId { get; set; }

    public DateTime? ReturnDate { get; set; }

    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? ReturnCount { get; set; }

    public string ReturnContent { get; set; }

    public string ReturnImage { get; set; }

    public virtual ShopReturnStatusDataTable ProcessingStatus { get; set; }

    public virtual ShopReturnReasonDataTable ReturnReason { get; set; }
}