// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCouponTotal
{
    public int CouponId { get; set; }

    public string CouponName { get; set; }

    public string CouponContent { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public int? TotalQuantity { get; set; }

    public bool? Usable { get; set; }

    public decimal? SpecialOffer { get; set; }

    public string Image { get; set; }

    public virtual ICollection<ShopMemberCouponData> ShopMemberCouponData { get; set; } = new List<ShopMemberCouponData>();
}