// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCaseDataTable
{
    public int CaseId { get; set; }

    public int MessageId { get; set; }
}