// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopMemberCouponData
{
    public int? MemberId { get; set; }

    public int? CouponId { get; set; }

    public bool? CouponStatusId { get; set; }

    public int MemberCouponDataId { get; set; }

    public virtual ShopCouponTotal Coupon { get; set; }

    public virtual ShopMemberInfo Member { get; set; }
}