// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopMemberComplaintCase
{
    public int ComplaintCaseId { get; set; }

    public string ComplaintTitle { get; set; }

    public int? MemberId { get; set; }

    public string ComplaintContent { get; set; }

    public int? ComplaintStatusId { get; set; }

    public int? ComplaintCategoryId { get; set; }

    public DateTime? CreationTime { get; set; }

    public virtual ShopAppealCategoryData ComplaintCategory { get; set; }

    public virtual ShopComplaintStatusData ComplaintStatus { get; set; }

    public virtual ShopMemberInfo Member { get; set; }

    public virtual ICollection<ShopReplyData> ShopReplyData { get; set; } = new List<ShopReplyData>();
}