// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopRoom
{
    public int RoomId { get; set; }

    public DateTime? CheckInDate { get; set; }

    public DateTime? CheckOffDate { get; set; }

    public int? ProductId { get; set; }

    public virtual ShopProductTotal Product { get; set; }
}