// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopProductCategory
{
    public int ProductCategoryId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public virtual ICollection<ShopProductTotal> ShopProductTotal { get; set; } = new List<ShopProductTotal>();
}