// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopOrderDetailTable
{
    public int? OrderId { get; set; }

    public int? ProductId { get; set; }

    public int? ProductQuantity { get; set; }

    public int OrderDetailId { get; set; }

    public virtual ShopOrderTotalTable Order { get; set; }

    public virtual ShopProductTotal Product { get; set; }
}