// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCatStatus
{
    public int CatId { get; set; }

    public int? MyCatListId { get; set; }

    public string CatName { get; set; }

    public int? CatAge { get; set; }

    public int? CatPersonalityId { get; set; }

    public int MemberId { get; set; }

    public virtual ShopCatcharacter CatPersonality { get; set; }

    public virtual ShopMemberInfo Member { get; set; }

    public virtual ShopMyCatNameList MyCatList { get; set; }
}